"""
Comprehensive artifact set database for CritCal.
Fields: type, pieces, 2_piece_bonus, 4_piece_bonus,
best_for, recommended_stats, recommended_characters, tags, domain, updated
"""

ARTIFACTS_DB = {
    "a day carved from rising winds": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Anemo DMG +15%.',
    "4_piece_bonus": 'After Swirl, party gains 20% Elemental DMG Bonus for 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['anemo', 'swirl', 'support'],
    "domain": "",
    "updated": "2026-07",
    },
    "adventurer": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Max HP +1,000.',
    "4_piece_bonus": 'Opening a chest regenerates 30% Max HP over 5s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['early_game', 'exploration'],
    "domain": "",
    "updated": "2026-07",
    },
    "archaic petra": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Geo DMG Bonus +15%.',
    "4_piece_bonus": 'Upon obtaining a Crystallize Shard, party members gain 35% Elemental DMG Bonus for that element for 10s. Only one bonus can exist at a time.',
    "best_for": ['Zhongli', 'Ningguang'],
    "recommended_stats": {},
    "recommended_characters": ['Zhongli', 'Ningguang'],
    "tags": ['geo', 'support', 'crystallize', 'team_buffer'],
    "domain": "",
    "updated": "2026-07",
    },
    "berserker": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'CRIT Rate +12%.',
    "4_piece_bonus": 'When HP is below 70%, CRIT Rate increases by an additional 24%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['crit_rate', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "blizzard strayer": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Cryo DMG Bonus +15%.',
    "4_piece_bonus": 'CRIT Rate increased by 20% when attacking enemies affected by Cryo. If the enemy is Frozen, CRIT Rate is increased by an additional 20%.',
    "best_for": ['Ayaka', 'Ganyu', 'Kaeya'],
    "recommended_stats": {},
    "recommended_characters": ['Ayaka', 'Ganyu', 'Kaeya'],
    "tags": ['cryo', 'crit_rate', 'freeze', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "bloodstained chivalry": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Physical DMG Bonus +25%.',
    "4_piece_bonus": 'After defeating an opponent, increases Charged Attack DMG by 50% and reduces its stamina cost to 0 for 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['physical', 'charged_atk'],
    "domain": "",
    "updated": "2026-07",
    },
    "brave heart": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'Increases DMG by 30% against enemies with more than 50% HP.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "crimson witch of flames": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Pyro DMG Bonus +15%.',
    "4_piece_bonus": 'Increases Overloaded, Burning, and Burgeon DMG by 40%. Increases Vaporize and Melt DMG by 15%. Using an Elemental Skill increases 2pc effect by 50% for 10s (max 3 stacks).',
    "best_for": ['Hu Tao', 'Diluc', 'Xiangling', 'Yanfei', 'Klee'],
    "recommended_stats": {},
    "recommended_characters": ['Hu Tao', 'Diluc', 'Xiangling', 'Yanfei', 'Klee'],
    "tags": ['pyro', 'reaction', 'vaporize', 'melt', 'overload'],
    "domain": "",
    "updated": "2026-07",
    },
    "deepwood memories": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Dendro DMG Bonus +15%.',
    "4_piece_bonus": 'Elemental Skill or Burst hits decrease enemy Dendro RES by 30% for 8s. Effective even when off-field.',
    "best_for": ['Nahida', 'Baizhu', 'Collei', 'Dendro Traveler'],
    "recommended_stats": {},
    "recommended_characters": ['Nahida', 'Baizhu', 'Collei', 'Dendro Traveler'],
    "tags": ['dendro', 'support', 'res_shred', 'dendro_res_shred'],
    "domain": "",
    "updated": "2026-07",
    },
    "defender's will": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'DEF +30%.',
    "4_piece_bonus": 'For each party member with a different Elemental Type, increases Elemental RES by 30%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['def_scaling', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "desert pavilion chronicle": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Anemo DMG Bonus +15%.',
    "4_piece_bonus": 'After a Charged Attack hits, Normal Attack SPD increases by 10% and Normal, Charged, and Plunging Attack DMG increases by 30% for 10s.',
    "best_for": ['Wanderer', 'Xiao'],
    "recommended_stats": {},
    "recommended_characters": ['Wanderer', 'Xiao'],
    "tags": ['anemo', 'normal_atk', 'charged_atk', 'plunge', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "disenchantment in deep shadow": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Cryo DMG +15%.',
    "4_piece_bonus": 'Deal 25% more DMG vs Cryo-affected enemies.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['cryo', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "echoes of an offering": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'Normal Attacks have a 36% chance to trigger Valley Rite, increasing Normal Attack DMG by 70% of ATK. Effect removed 0.05s after a Normal Attack deals DMG.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'normal_atk', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "emblem of severed fate": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Energy Recharge +20%.',
    "4_piece_bonus": 'Increases Elemental Burst DMG by 25% of Energy Recharge (max 75%).',
    "best_for": ['Raiden Shogun', 'Xiangling', 'Xingqiu', 'Yelan', 'Beidou'],
    "recommended_stats": {},
    "recommended_characters": ['Raiden Shogun', 'Xiangling', 'Xingqiu', 'Yelan', 'Beidou'],
    "tags": ['er', 'burst_dmg', 'universal'],
    "domain": "",
    "updated": "2026-07",
    },
    "finale of the deep (artifact)": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Healing effectiveness +15%.',
    "4_piece_bonus": 'After the wielder is healed, all party members deal 14% more Elemental Skill DMG for 10s. Can occur once every 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['healing', 'support', 'skill_dmg', 'team_buffer', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "finale of the deep galleries": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ER +20%.',
    "4_piece_bonus": 'After skill, party gains 10% Elemental DMG Bonus for 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['er', 'support', 'team_buffer'],
    "domain": "",
    "updated": "2026-07",
    },
    "flower of paradise lost": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Mastery +80.',
    "4_piece_bonus": 'Bloom, Hyperbloom, and Burgeon DMG increased by 40%. Additionally, triggering any of these reactions increases the bonus by 25% (max 4 stacks). Can occur once per second.',
    "best_for": ['Kuki Shinobu', 'Nilou', 'Thoma'],
    "recommended_stats": {},
    "recommended_characters": ['Kuki Shinobu', 'Nilou', 'Thoma'],
    "tags": ['em', 'bloom', 'hyperbloom', 'burgeon', 'reaction'],
    "domain": "",
    "updated": "2026-07",
    },
    "fragment of harmonic whimsy": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'When Bond of Life changes, deal 25% more DMG for 8s (max 3).',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'bond_of_life', 'dps', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "gambler": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Skill DMG +20%.',
    "4_piece_bonus": 'Defeating an opponent has a 100% chance to reset Elemental Skill CD. Can occur once every 15s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['skill_dmg', 'skill_reset', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "gilded dreams": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Mastery +80.',
    "4_piece_bonus": 'For each party member with a different element, the wielder gains 50 ATK and 50 EM. For each same element, gains 50 ATK. Max 4 stacks.',
    "best_for": ['Alhaitham', 'Cyno', 'Nahida'],
    "recommended_stats": {},
    "recommended_characters": ['Alhaitham', 'Cyno', 'Nahida'],
    "tags": ['em', 'atk_scaling', 'reaction', 'dendro'],
    "domain": "",
    "updated": "2026-07",
    },
    "gladiator's finale": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'If the wielder uses a Sword, Claymore, or Polearm, increases Normal Attack DMG by 35%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'normal_atk', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "golden troupe": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Skill DMG +20%.',
    "4_piece_bonus": "Elemental Skill DMG increases by 25% of the wielder's Total DEF. Additionally, while off-field, Elemental Skill DMG increases by a further 25%.",
    "best_for": ['Furina', 'Fischl', 'Yae Miko', 'Albedo', 'Chiori'],
    "recommended_stats": {},
    "recommended_characters": ['Furina', 'Fischl', 'Yae Miko', 'Albedo', 'Chiori'],
    "tags": ['skill_dmg', 'off_field', 'def_scaling', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "heart of depth": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Hydro DMG Bonus +15%.',
    "4_piece_bonus": 'After using an Elemental Skill, increases Normal and Charged Attack DMG by 30% for 15s.',
    "best_for": ['Childe', 'Ayato', 'Kokomi'],
    "recommended_stats": {},
    "recommended_characters": ['Childe', 'Ayato', 'Kokomi'],
    "tags": ['hydro', 'normal_atk', 'charged_atk', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "husk of opulent dreams": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'DEF +30%.',
    "4_piece_bonus": 'A character gains Curiosity stacks (max 4) when dealing Geo DMG or while off-field for 3s. Each stack increases DEF by 6% and Geo DMG by 6%.',
    "best_for": ['Itto', 'Noelle', 'Albedo', 'Chiori', 'Gorou'],
    "recommended_stats": {},
    "recommended_characters": ['Itto', 'Noelle', 'Albedo', 'Chiori', 'Gorou'],
    "tags": ['def_scaling', 'geo', 'dps', 'support'],
    "domain": "",
    "updated": "2026-07",
    },
    "initiate": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +10%.',
    "4_piece_bonus": '',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "instructor's": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Mastery +80.',
    "4_piece_bonus": 'After triggering a reaction, increases party EM by 120 for 8s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['em', 'support', 'team_buffer', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "lavawalker": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Pyro RES +40%.',
    "4_piece_bonus": 'Increases DMG dealt by 35% against enemies affected by Pyro.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['pyro', 'mono_pyro', 'conditional'],
    "domain": "",
    "updated": "2026-07",
    },
    "long night's oath": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Physical DMG Bonus +25%.',
    "4_piece_bonus": 'After party members trigger Nightsoul Transmission, the equipping character gains 35% increased Charged Attack DMG and 5% increased CRIT Rate for 6s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['physical', 'charged_atk', 'crit_rate', 'natlan'],
    "domain": "",
    "updated": "2026-07",
    },
    "lucky dog": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'DEF +100.',
    "4_piece_bonus": 'Picking up Mora restores 300 HP.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['early_game', 'exploration'],
    "domain": "",
    "updated": "2026-07",
    },
    "maiden beloved": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Healing effectiveness +15%.',
    "4_piece_bonus": 'Using an Elemental Skill or Burst increases party healing received by 20% for 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['healing', 'support', 'healer'],
    "domain": "",
    "updated": "2026-07",
    },
    "marechaussee hunter": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Normal and Charged Attack DMG +15%.',
    "4_piece_bonus": 'When HP increases or decreases, CRIT Rate increases by 12% for 5s. Max 3 stacks.',
    "best_for": ['Neuvillette', 'Wriothesley', 'Lyney', 'Furina'],
    "recommended_stats": {},
    "recommended_characters": ['Neuvillette', 'Wriothesley', 'Lyney', 'Furina'],
    "tags": ['crit_rate', 'normal_atk', 'charged_atk', 'hp_fluctuation', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "martial artist": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Normal and Charged ATK DMG +15%.',
    "4_piece_bonus": 'After using an Elemental Skill, Normal and Charged Attack DMG increased by 25% for 8s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['normal_atk', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "night of the sky's unveiling": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Mastery +80.',
    "4_piece_bonus": 'After a reaction, party gains 60 EM for 12s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['em', 'support', 'team_buffer'],
    "domain": "",
    "updated": "2026-07",
    },
    "nighttime whispers in the echoing woods": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'After using an Elemental Skill, gain 20% Geo DMG Bonus for 10s. While shielded, Geo DMG Bonus increases by a further 150%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'geo', 'shield', 'dps', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "noblesse oblige": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Burst DMG +20%.',
    "4_piece_bonus": 'Using an Elemental Burst increases party ATK by 20% for 12s.',
    "best_for": ['Bennett', 'Mona', 'Sara', 'Diona', 'Faruzan'],
    "recommended_stats": {},
    "recommended_characters": ['Bennett', 'Mona', 'Sara', 'Diona', 'Faruzan'],
    "tags": ['burst_dmg', 'support', 'team_buffer', 'universal'],
    "domain": "",
    "updated": "2026-07",
    },
    "nymph's dream": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Hydro DMG Bonus +15%.',
    "4_piece_bonus": 'After Normal, Charged, or Plunging attacks, Elemental Skills, or Elemental Bursts hit, gain a stack of 25% ATK and 15% Hydro DMG (max 3 stacks).',
    "best_for": ['Childe', 'Ayato'],
    "recommended_stats": {},
    "recommended_characters": ['Childe', 'Ayato'],
    "tags": ['hydro', 'atk_scaling', 'dps', 'normal_atk', 'skill_dmg'],
    "domain": "",
    "updated": "2026-07",
    },
    "obsidian codex": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": "When the wielder is in Nightsoul's Blessing and on field, all DMG dealt increases by 15%.",
    "4_piece_bonus": "After the wielder consumes 20 Nightsoul points, CRIT Rate increases by 25% while in Nightsoul's Blessing for 10s.",
    "best_for": ['Mavuika', 'Chasca', 'Kinich', 'Mualani'],
    "recommended_stats": {},
    "recommended_characters": ['Mavuika', 'Chasca', 'Kinich', 'Mualani'],
    "tags": ['crit_rate', 'nightsoul', 'natlan', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "ocean-hued clam": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Healing Bonus +15%.',
    "4_piece_bonus": 'When the wielder heals, accumulates a Sea-Dyed Foam for 3s. When it expires, deals physical DMG equal to 90% of the accumulated healing (max 30,000 HP).',
    "best_for": ['Kokomi', 'Qiqi', 'Barbara'],
    "recommended_stats": {},
    "recommended_characters": ['Kokomi', 'Qiqi', 'Barbara'],
    "tags": ['healing', 'physical', 'sub_dps', 'healer'],
    "domain": "",
    "updated": "2026-07",
    },
    "pale flame": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Physical DMG Bonus +25%.',
    "4_piece_bonus": 'When an Elemental Skill hits, ATK increases by 9% for 7s (max 2 stacks). At 2 stacks, Physical 2pc bonus doubles.',
    "best_for": ['Eula', 'Razor', 'Xinyan'],
    "recommended_stats": {},
    "recommended_characters": ['Eula', 'Razor', 'Xinyan'],
    "tags": ['physical', 'skill_dmg', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "prayers for destiny": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Hydro RES +40%.',
    "4_piece_bonus": '',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['defensive'],
    "domain": "",
    "updated": "2026-07",
    },
    "prayers for illumination": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Pyro RES +40%.',
    "4_piece_bonus": '',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['defensive'],
    "domain": "",
    "updated": "2026-07",
    },
    "prayers for wisdom": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Electro RES +40%.',
    "4_piece_bonus": '',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['defensive'],
    "domain": "",
    "updated": "2026-07",
    },
    "prayers to springtime": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Cryo RES +40%.',
    "4_piece_bonus": '',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['defensive'],
    "domain": "",
    "updated": "2026-07",
    },
    "resolution of sojourner": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'Charged Attack CRIT Rate +30%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['atk_scaling', 'charged_atk', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "retracing bolide": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Shield Strength +35%.',
    "4_piece_bonus": 'While shielded, gain 40% additional Normal and Charged Attack DMG.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['shield', 'normal_atk', 'charged_atk', 'conditional'],
    "domain": "",
    "updated": "2026-07",
    },
    "scholar": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Energy Recharge +20%.',
    "4_piece_bonus": 'Gaining Elemental Particles or Orbs regenerates 3 Energy for all party members with a bow or catalyst. Can occur once every 3s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['er', 'support', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "scroll of the hero of cinder city": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'When a nearby party member triggers a Nightsoul Transmission, the equipping character gains 6 Nightsoul points.',
    "4_piece_bonus": 'When the wielder triggers a reaction, party members gain 28% Elemental DMG Bonus for the elements involved for 20s.',
    "best_for": ['Xilonen', 'Kachina', 'Chasca', 'Mavuika'],
    "recommended_stats": {},
    "recommended_characters": ['Xilonen', 'Kachina', 'Chasca', 'Mavuika'],
    "tags": ['support', 'team_buffer', 'elemental_dmg', 'natlan'],
    "domain": "",
    "updated": "2026-07",
    },
    "shimenawa's reminiscence": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'When using an Elemental Skill with 15+ Energy, consume 15 Energy and increase Normal/Charged/Plunging Attack DMG by 50% for 10s.',
    "best_for": ['Yoimiya', 'Hu Tao', 'Ganyu'],
    "recommended_stats": {},
    "recommended_characters": ['Yoimiya', 'Hu Tao', 'Ganyu'],
    "tags": ['atk_scaling', 'normal_atk', 'charged_atk', 'dps'],
    "domain": "",
    "updated": "2026-07",
    },
    "silken moon's serenade": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ER +20%.',
    "4_piece_bonus": 'After Burst, party gains 12% Elemental DMG Bonus for 12s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['er', 'support', 'team_buffer'],
    "domain": "",
    "updated": "2026-07",
    },
    "song of days past": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Healing Bonus +15%.',
    "4_piece_bonus": 'When the wielder heals, records healing for 8s. When the record reaches 15,000, creates a 10s field that increases party DMG by 8% of the healing recorded (max 1,200 per trigger).',
    "best_for": ['Xianyun', 'Sigewinne', 'Charlotte'],
    "recommended_stats": {},
    "recommended_characters": ['Xianyun', 'Sigewinne', 'Charlotte'],
    "tags": ['healing', 'support', 'team_buffer', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "tenacity of the millelith": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'HP +20%.',
    "4_piece_bonus": 'When an Elemental Skill hits, party ATK increases by 20% and Shield Strength increases by 30% for 3s.',
    "best_for": ['Zhongli', 'Kokomi', 'Layla', 'Kuki Shinobu'],
    "recommended_stats": {},
    "recommended_characters": ['Zhongli', 'Kokomi', 'Layla', 'Kuki Shinobu'],
    "tags": ['hp_scaling', 'support', 'team_buffer', 'shield'],
    "domain": "",
    "updated": "2026-07",
    },
    "the exile": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Energy Recharge +20%.',
    "4_piece_bonus": 'Using an Elemental Burst regenerates 2 Energy for all party members (excluding the wielder) every 2s for 6s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['er', 'support', 'team_battery', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "thundering fury": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Electro DMG Bonus +15%.',
    "4_piece_bonus": 'Increases Overloaded, Electro-Charged, Superconduct, Hyperbloom, and Aggravate DMG by 40%. Electro reaction triggers reduce Skill CD by 1s. Can occur once every 0.8s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['electro', 'reaction', 'skill_cd', 'aggravate', 'hyperbloom'],
    "domain": "",
    "updated": "2026-07",
    },
    "thundersoother": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Electro RES +40%.',
    "4_piece_bonus": 'Increases DMG dealt by 35% against enemies affected by Electro.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['electro', 'mono_electro', 'conditional'],
    "domain": "",
    "updated": "2026-07",
    },
    "tiny miracle": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'All Elemental RES +20%.',
    "4_piece_bonus": 'Incoming Elemental DMG increases corresponding Elemental RES by 30% for 10s. Can occur once every 10s.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['defensive', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "traveling doctor": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Incoming healing +20%.',
    "4_piece_bonus": 'Using an Elemental Burst restores 20% HP.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['healing', 'early_game'],
    "domain": "",
    "updated": "2026-07",
    },
    "unfinished reverie": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'After leaving combat for more than 3s, gain 50% increased DMG dealt for 10s. While burning, this increases by 25%.',
    "best_for": ['Emilie', 'Kinich'],
    "recommended_stats": {},
    "recommended_characters": ['Emilie', 'Kinich'],
    "tags": ['atk_scaling', 'burning', 'dps', 'fontaine'],
    "domain": "",
    "updated": "2026-07",
    },
    "vermillion hereafter": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'ATK +18%.',
    "4_piece_bonus": 'After using an Elemental Burst, gain a Nascent Light effect for 16s, increasing ATK by 8% every second. When the wielder loses HP, ATK increases by a further 10% (max 4 stacks).',
    "best_for": ['Xiao'],
    "recommended_stats": {},
    "recommended_characters": ['Xiao'],
    "tags": ['atk_scaling', 'burst_focus', 'hp_fluctuation', 'xiao'],
    "domain": "",
    "updated": "2026-07",
    },
    "viridescent venerer": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Anemo DMG Bonus +15%.',
    "4_piece_bonus": "Swirl DMG increased by 60%. Decreases opponent's Elemental RES to the infused element by 40% for 10s.",
    "best_for": ['Kazuha', 'Venti', 'Sucrose', 'Jean', 'Heizou'],
    "recommended_stats": {},
    "recommended_characters": ['Kazuha', 'Venti', 'Sucrose', 'Jean', 'Heizou'],
    "tags": ['anemo', 'support', 'res_shred', 'swirl', 'em'],
    "domain": "",
    "updated": "2026-07",
    },
    "vourukasha's glow": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'HP +20%.',
    "4_piece_bonus": 'Elemental Skill and Burst DMG increased by 10%. When the wielder takes DMG, this effect increases by 80% for 5s. Can occur once every 0.1s. Max 5 stacks.',
    "best_for": ['Dehya', 'Nilou'],
    "recommended_stats": {},
    "recommended_characters": ['Dehya', 'Nilou'],
    "tags": ['hp_scaling', 'skill_dmg', 'burst_dmg', 'dps', 'sumeru'],
    "domain": "",
    "updated": "2026-07",
    },
    "wanderer's troupe": {
    "type": "artifact_set",
    "pieces": 5,
    "2_piece_bonus": 'Elemental Mastery +80.',
    "4_piece_bonus": 'If the wielder uses a Catalyst or Bow, Charged Attack DMG increases by 35%.',
    "best_for": [],
    "recommended_stats": {},
    "recommended_characters": [],
    "tags": ['em', 'charged_atk', 'catalyst', 'bow'],
    "domain": "",
    "updated": "2026-07",
    },
}
